FROM docker.io/centos/python-35-centos7

MAINTAINER 649788479@qq.com

ARG PYTHON_VERSION=3.5.1

#ADD ./requirements.txt /tmp/

RUN set -x
#    && pip install --upgrade pip \
#    && pip install -r /tmp/requirements.txt \
#    && chmod +w /tmp/requirements.txt

VOLUME /workspace
WORKDIR /workspace
